# Generated by Django 6.0 on 2025-12-20 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('mobile1', models.CharField(max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15)),
                ('joining_date', models.DateField()),
                ('open_unit', models.IntegerField(default=0)),
                ('base_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('rent_date', models.DateField()),
                ('base_rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_unit', models.IntegerField(default=0)),
                ('close_unit', models.IntegerField(blank=True, null=True)),
                ('units_used', models.IntegerField(blank=True, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='homerent_mainapp.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'month', 'year')},
            },
        ),
    ]
