# Generated by Django 6.0 on 2025-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homerent_mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_photos/'),
        ),
    ]
